//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZLibModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.copy = new HashSet<copy>();
        }
    
        public string isbn { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string price { get; set; }
        public string edition { get; set; }
    
        public virtual ICollection<copy> copy { get; set; }
    }
}
