//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZLibModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.record = new HashSet<record>();
            this.record1 = new HashSet<record>();
        }
    
        public string user1 { get; set; }
        public string password { get; set; }
        public sbyte duration { get; set; }
        public bool isadmin { get; set; }
        public string token { get; set; }
    
        public virtual ICollection<record> record { get; set; }
        public virtual ICollection<record> record1 { get; set; }
    }
}
